#!/bin/bash
usage()
{
cat << EOF

rsync files to a (dropbox) location, filtering on .gitignore files

USAGE:

dropbak <source> <destination> [interval]

OPTIONS:
    -h      show usage info
    -i      interval time to run [seconds]
    -d      delay initial run by [seconds]

EOF
exit 1
}

if [ -z "$2" ];then
  usage
fi

OPTIND=3
while getopts "hi:d:" option
do
  case $option in
    h) usage;;
    i) INTERVAL=$OPTARG;;
    d) DELAY=$OPTARG;;
    \?) usage;exit 2;;
  esac
done

if [ ! -z "$DELAY" ];then
  SLEEP "$DELAY"
fi

if [ -z "$INTERVAL" ];then
  INTERVAL=300
fi

while true; do
  T="$(date +%s)"
  rsync -ra --delete --stats --human-readable --filter=':- .gitignore' --filter=".- $HOME/.gitignore" "$1" "$2"
  T="$(($(date +%s)-T))"
  let D=INTERVAL-T
  if [ $D -gt 0 ]; then
    sleep $D
  fi
done
