#!/bin/bash
usage()
{
cat << EOF

rsync files to a (dropbox) location, filtering on .gitignore and .dbignore files

USAGE:

dropbak <source> <destination> [interval]

OPTIONS:
    -h      show usage info
    -i      interval time to run [seconds]
    -d      delay initial run by [seconds]

EOF
exit 1
}

if [ -z "$2" ];then
  usage
fi

OPTIND=3
while getopts "hi:d:" option
do
  case $option in
    h) usage;;
    i) INTERVAL=$OPTARG;;
    d) DELAY=$OPTARG;;
    \?) usage;exit 2;;
  esac
done

if [ ! -z "$DELAY" ];then
  SLEEP "$DELAY"
fi

if [ -z "$INTERVAL" ];then
  INTERVAL=300
fi

FILTER_DBIGNORE=("--filter=:- .dbignore_global")
if [ -f "$HOME/.dbignore_global" ];then
  FILTER_DBIGNORE+=("--filter=.- $HOME/.dbignore_global")
fi

FILTER_GITIGNORE=("--filter=:- .gitignore_global")
if [ -f "$HOME/.gitignore_global" ];then
  FILTER_GITIGNORE+=("--filter=.- $HOME/.gitignore_global")
fi

while true; do
  T="$(date +%s)"
  rsync -ra --delete --stats --human-readable "${FILTER_DBIGNORE[@]}" "${FILTER_GITIGNORE[@]}" "$1" "$2"
  T="$(($(date +%s)-T))"
  let D=INTERVAL-T
  if [ $D -gt 0 ]; then
    sleep $D
  fi
done
